PROJECT_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST)))).

TARGET = connect

ifeq ($(RELEASE), yes)

OPTLEVEL = 3
DBGLEVEL = 0
CPPDEFS = 

else

OPTLEVEL = 0
DBGLEVEL = 3
CPPDEFS = DEBUG

endif


#C++ Source files
CXXSRCS = $(PROJECT_PATH)/connect.cpp


#Include directories and macros
INCDIRS = $(PROJECT_PATH)/../inc

CPPDEFS +=

CXXFLAGS += -Wno-unused-parameter
LDFLAGS += -lstdc++ -lbluetooth -ldbus-1

LIBS += $(PROJECT_PATH)/../powermon_lib.a

include $(PROJECT_PATH)/build.mk
